DROP DATABASE IF EXISTS BD_ACADEMICO;
CREATE DATABASE BD_ACADEMICO;
USE BD_ACADEMICO;
-- MODELO OPERACIONAL DO BANCO DE DADOS ACADEMICO

CREATE TABLE CURSO (
	CO_CURSO		INT			NOT NULL,
    NOME			CHAR(40)	NULL
);
ALTER TABLE CURSO ADD CONSTRAINT PK_CURSO PRIMARY KEY (CO_CURSO);

CREATE TABLE TURMA (
	CO_TURMA	CHAR(11)		NOT NULL,
    ANO			CHAR(4)			NULL,
    PERIODO		CHAR(1)			NULL,
    DESCRICAO	CHAR(50)		NULL,
    DT_INICIAL	DATETIME		NULL,
    DT_FINAL	DATETIME		NULL,
    NUM_PROVAS	INT				NULL,
    CO_CURSO	INT				NULL    
);
ALTER TABLE TURMA ADD CONSTRAINT PK_TURMA PRIMARY KEY (CO_TURMA);
ALTER TABLE TURMA ADD CONSTRAINT FK_TURMA_CURSO FOREIGN KEY (CO_CURSO) REFERENCES CURSO (CO_CURSO);

CREATE TABLE PROFESSOR (
	CO_PROFESSOR	INT			NOT NULL,
    SG_SEXO			CHAR(1)		NULL,
    NOME			VARCHAR(20) NULL,
    DT_NASCIMENTO	DATETIME	NULL
);
ALTER TABLE PROFESSOR ADD CONSTRAINT PK_PROFESSOR PRIMARY KEY (CO_PROFESSOR);

CREATE TABLE ALUNO (
	CO_ALUNO		INT			NOT NULL,
    DT_NASCIMENTO	DATETIME	NULL,
    SG_SEXO			CHAR(1)		NULL,
    HOME			VARCHAR(20)	NULL,
    CO_ESTADOCIVIL	CHAR(1)		NULL,
    NO_PAI			VARCHAR(70) NULL,
    NO_MAE			VARCHAR(70)	NULL
);
ALTER TABLE ALUNO ADD CONSTRAINT PK_ALUNO PRIMARY KEY (CO_ALUNO);

CREATE TABLE ALUNO_TURMA (
	CO_ALUNO		INT			NOT NULL,
    CO_TURMA		CHAR(11)	NOT NULL,
    DT_MATRICULA	DATETIME	NULL,
    DT_CANCELAMENTO	DATETIME	NULL
);
ALTER TABLE ALUNO_TURMA ADD CONSTRAINT PK_ALUNO_TURMA PRIMARY KEY (CO_ALUNO, CO_TURMA);
ALTER TABLE ALUNO_TURMA ADD CONSTRAINT FK_ALUNO_TURMA_ALUNO FOREIGN KEY (CO_ALUNO) REFERENCES ALUNO (CO_ALUNO);
ALTER TABLE ALUNO_TURMA ADD CONSTRAINT FK_ALUNO_TURMA_TURMA FOREIGN KEY (CO_TURMA) REFERENCES TURMA (CO_TURMA);

CREATE TABLE PROVA (
	CO_PROVA	CHAR(3)		NOT NULL,
    DS_PROVA	VARCHAR(20)	NULL
);
ALTER TABLE PROVA ADD CONSTRAINT PK_PROVA PRIMARY KEY (CO_PROVA);

CREATE TABLE DISCIPLINA (
	CO_DISCIPLINA	CHAR(2)		NOT NULL,
    NO_DISCIPLINA	VARCHAR(30)	NULL
);
ALTER TABLE DISCIPLINA ADD CONSTRAINT PK_DISCIPLINA PRIMARY KEY (CO_DISCIPLINA);

CREATE TABLE AVALIACAO (
	CO_ALUNO		INT			NOT NULL,
    CO_TURMA		CHAR(11)	NOT NULL,
    CO_DISCIPLINA	CHAR(2)		NOT NULL,
    CO_PROVA		CHAR(3)		NOT NULL,
    DT_AVALIACAO	DATETIME	NULL,
    NT_AVALIACA		FLOAT(53)	NULL
);
ALTER TABLE AVALIACAO ADD CONSTRAINT PK_AVALIACAO PRIMARY KEY(CO_ALUNO, CO_TURMA, CO_DISCIPLINA, CO_PROVA);
ALTER TABLE AVALIACAO ADD CONSTRAINT FK_AVALIACAO_ALUNO_TURMA FOREIGN KEY (CO_ALUNO, CO_TURMA) REFERENCES ALUNO_TURMA (CO_ALUNO, CO_TURMA);
ALTER TABLE AVALIACAO ADD CONSTRAINT FK_AVALIACAO_DISCIPLINA FOREIGN KEY (CO_DISCIPLINA) REFERENCES DISCIPLINA (CO_DISCIPLINA);
ALTER TABLE AVALIACAO ADD CONSTRAINT FK_AVALIACAO_PROVA FOREIGN KEY (CO_PROVA) REFERENCES PROVA (CO_PROVA);

CREATE TABLE PROF_TURM_DISC (
	CO_PROFESSOR	INT 	NOT NULL,
    CO_TURMA	    CHAR(11)NOT NULL,
    CO_DISCIPLINA	CHAR(2) NOT NULL
);
ALTER TABLE PROF_TURM_DISC ADD CONSTRAINT PK_PROF_TURM_DISC PRIMARY KEY (CO_PROFESSOR, CO_TURMA, CO_DISCIPLINA);
ALTER TABLE PROF_TURM_DISC ADD CONSTRAINT FK_PROF_TURM_DISC_PROFESSOR FOREIGN KEY (CO_PROFESSOR) REFERENCES PROFESSOR (CO_PROFESSOR);
ALTER TABLE PROF_TURM_DISC ADD CONSTRAINT FK_PROF_TURM_DISC_TURMA FOREIGN KEY (CO_TURMA) REFERENCES TURMA (CO_TURMA);
ALTER TABLE PROF_TURM_DISC ADD CONSTRAINT FK_PROF_TURM_DISC_DISCIPLINA FOREIGN KEY (CO_DISCIPLINA) REFERENCES DISCIPLINA (CO_DISCIPLINA);

CREATE TABLE FREQUENCIA (
	CO_ALUNO		INT 		NOT NULL,
    CO_TURMA		CHAR(11)	NOT NULL,
    CO_DISCIPLINA	CHAR(2)		NOT NULL,
    DT_FREQUENCIA	DATETIME	NOT NULL,
    FREQUENCIA		CHAR(1)		NULL
);
ALTER TABLE FREQUENCIA ADD CONSTRAINT PK_FREQUENCIA PRIMARY KEY (CO_ALUNO, CO_TURMA, CO_DISCIPLINA, DT_FREQUENCIA);
ALTER TABLE FREQUENCIA ADD CONSTRAINT FK_FREQUENCIA_ALUNO FOREIGN KEY (CO_ALUNO) REFERENCES ALUNO (CO_ALUNO);
ALTER TABLE FREQUENCIA ADD CONSTRAINT FK_FREQUENCIA_TURMA FOREIGN KEY (CO_TURMA) REFERENCES TURMA (CO_TURMA);
ALTER TABLE FREQUENCIA ADD CONSTRAINT FK_FREQUENCIA_ALUNO_TURMA FOREIGN KEY (CO_ALUNO, CO_TURMA) REFERENCES ALUNO_TURMA (CO_ALUNO, CO_TURMA);
